### PR TITLE
Added all the Tiago source files and ws precompiled

### PR DESCRIPTION
**Pull request by pulver22**
This PR aims at fixing #6.

@Melanoneiro it seems that despite the workspace in `ros_ws` being precompiled and source, the packages `lcastor_XXX` are not found immediately after launching the image. The user is forced to compile the workspace again and source it manually. I don't understand why (this doesn't happen for the packages `tiago_XXX` which are in the same workspace). Can you please have a look and help me to fix it? I've already spent the entire afternoon 😫

### CODE REVIEW

**Comment by pulver22** [comment]
It seems that only the `tiago_XXX` packages are compiled. To be honest, at which point is the LCASTOR repo cloned into `ros_ws/src`? That may be the reason why it's not working (it's cloned after I compile the workspace).

**Comment by Melanoneiro** [comment]
With the existing scripts, only the actual LCASTOR directory is automatically mounted into the workspace. The recompilation inside the workspace is intentional to make sure all the right packages are linked and such from inside the container. I will look into automatically mounting the other directories and possibly auto-building the workspace as soon as I have time.

**Comment by pulver22** [comment]
Ok, I should have fixed it by working on the entrypoint.sh @Melanoneiro. I have to test now the tmule file @francescodelduchetto included and then I will ask you to review it!

**Comment by francescodelduchetto** [comment]
@pulver22 and @Melanoneiro can you please check it still works for you with the changes I have made? Also, check that you can pull the image from the lcas registry now https://github.com/LCAS/LCASTOR/wiki/Developing-with-Docker.

**Comment by pulver22** [comment]
I pushed a small fix to the Dockerfile as discussed this morning with @francescodelduchetto . The only bit missing would be to use the host user inside the docker image to prevent access right issues across the host and the image. I did an attempt but it needs further investigation because something was not working properly (e.g., password authentication was not working).

**Comment by pulver22** [comment]
Please @francescodelduchetto can you review this? Hopefully, it will be done after the last commit!

**Comment by francescodelduchetto** [comment]
Okay! It all works fine :) I am going to merge this

**Review by francescodelduchetto — APPROVED** [review]

**Pull request merged**
